In [5]:
import numpy as np

a = np.array([3,3,3])
b = np.array([3,3,3]).T
A = np.diag(np.ones(3))
print(a@A@b)

27.0


In [19]:
c = np.diag([1,2,3])
d = np.linalg.inv(c)

print(d)

I           = np.diag(np.ones(4)) 
print(I)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
dt = 1

Qw = np.array([0.1 ** 2, 0.1 ** 2, np.deg2rad(1) ** 2])             # covariance of the acceleration according to 3 axises (x, y, heading)
Qk = np.block([1/2 * Qw * dt**2, Qw * dt])
Qk = np.diag(Qk)  

print(Qk)

[[0.005      0.         0.         0.         0.         0.        ]
 [0.         0.005      0.         0.         0.         0.        ]
 [0.         0.         0.00015231 0.         0.         0.        ]
 [0.         0.         0.         0.01       0.         0.        ]
 [0.         0.         0.         0.         0.01       0.        ]
 [0.         0.         0.         0.         0.         0.00030462]]


In [8]:
zk = np.zeros((0, 1))  # empty vector
Rk = np.zeros((0, 0))  # empty matrix

print(Rk)

[]


In [3]:

        
Qk = np.diag(np.array([0.1 ** 2, 0.1 ** 2, np.deg2rad(5) ** 2]))  # covariance of simulated displacement noise

noise = np.random.normal(0, Qk.diagonal())

print(noise)

[ 0.01664865  0.0077351  -0.00369868]


In [16]:
a = np.zeros((0,1))

b = np.zeros((1,2))

print(a.size)

0
