In [3]:
import numpy as np

a = np.array([3,3,3])
b = np.array([3,3,3]).T
A = np.diag(np.ones(3))
print(a@A@b)

27.0


In [19]:
c = np.diag([1,2,3])
d = np.linalg.inv(c)

print(d)

I           = np.diag(np.ones(4)) 
print(I)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
dt = 1

Qw = np.array([0.1 ** 2, 0.1 ** 2, np.deg2rad(1) ** 2])             # covariance of the acceleration according to 3 axises (x, y, heading)
Qk = np.block([1/2 * Qw * dt**2, Qw * dt])
Qk = np.diag(Qk)  

print(Qk)

[[0.005      0.         0.         0.         0.         0.        ]
 [0.         0.005      0.         0.         0.         0.        ]
 [0.         0.         0.00015231 0.         0.         0.        ]
 [0.         0.         0.         0.01       0.         0.        ]
 [0.         0.         0.         0.         0.01       0.        ]
 [0.         0.         0.         0.         0.         0.00030462]]


In [8]:
zk = np.zeros((0, 1))  # empty vector
Rk = np.zeros((0, 0))  # empty matrix

print(Rk)

[]


In [3]:

        
Qk = np.diag(np.array([0.1 ** 2, 0.1 ** 2, np.deg2rad(5) ** 2]))  # covariance of simulated displacement noise

noise = np.random.normal(0, Qk.diagonal())

print(noise)

[ 0.01664865  0.0077351  -0.00369868]


In [16]:
a = np.zeros((0,1))

b = np.zeros((1,2))

print(a.size)

0


In [19]:
F = np.block([np.diag(np.ones(3)), np.zeros((3,1))])
print(F)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [9]:
a = np.empty((3,1))
print(a)

[[3.]
 [3.]
 [3.]]


In [3]:
from Feature import *
M = [CartesianFeature(np.array([[-40, 5]]).T),
           CartesianFeature(np.array([[-5, 40]]).T),
           CartesianFeature(np.array([[-5, 25]]).T),
           CartesianFeature(np.array([[-3, 50]]).T),
           CartesianFeature(np.array([[-20, 3]]).T),
           CartesianFeature(np.array([[40,-40]]).T)]  
print(M[1])

[[-5]
 [40]]


In [27]:
LIST = [np.array([1, 2, 3, 4, 5]), np.array([1, 2, 3, 4, 5]),np.array([1,2,3,4,5])] # inner lists are numpy arrays
print(np.concatenate( LIST, axis=0 ))
print(type(LIST[0]))

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
a = np.zeros((1,0))
print(a)
print(a.shape)
a = np.block([[a], [1]])
print(a)

[]
(1, 0)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
print(np.shape(a))

(3, 4)


In [4]:
import numpy as np
a = np.zeros((0,1))
b = np.zeros((2,1))

print(np.block([[a], [b]]))


[[0.]
 [0.]]


In [2]:
import numpy as np
a = np.array([[1,1], [1,1]])

print(np.shape(a))
for i in range(2,3):
    print(i)


(2, 2)
2
