In [21]:
import numpy as np

a = np.array([3,3,3])
b = np.array([3,3,3]).T
A = np.diag(np.ones(3))
print(a@A@b)

27.0


In [19]:
c = np.diag([1,2,3])
d = np.linalg.inv(c)

print(d)

I           = np.diag(np.ones(4)) 
print(I)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
